// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0uId9mTSUpcFcMVWW44N18n7YsRWY5Ec',
    appId: '1:314073085393:web:17098fabc8e3e17ce69cf0',
    messagingSenderId: '314073085393',
    projectId: 'app-alertaglobal-dev',
    authDomain: 'app-alertaglobal-dev.firebaseapp.com',
    storageBucket: 'app-alertaglobal-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI6xtxF1152jVaDbJYyWVT_yfBK9TjuhM',
    appId: '1:314073085393:android:bdc7d19f6eae577fe69cf0',
    messagingSenderId: '314073085393',
    projectId: 'app-alertaglobal-dev',
    storageBucket: 'app-alertaglobal-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiIUVmKeRPtIZr4-pwfcbPxGAVsGsjYIo',
    appId: '1:314073085393:ios:2a3ac126bef6be10e69cf0',
    messagingSenderId: '314073085393',
    projectId: 'app-alertaglobal-dev',
    storageBucket: 'app-alertaglobal-dev.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiIUVmKeRPtIZr4-pwfcbPxGAVsGsjYIo',
    appId: '1:314073085393:ios:2a3ac126bef6be10e69cf0',
    messagingSenderId: '314073085393',
    projectId: 'app-alertaglobal-dev',
    storageBucket: 'app-alertaglobal-dev.appspot.com',
    iosBundleId: 'com.example.example',
  );
}
